### ISSUE TITLE
@param tags for MultiChannelData struct

### ISSUE THREAD

**Issue by pakaplace** [STKtoken/Multi-Token-smart-contracts#40]
I haven't spent too, too much time looking through the contracts, but was wondering if you could add @params comments to the `MultiLibrary` struct in `MultiLibrary.sol`.  I'll definitely take a further look once I get a moment. Thanks for your contribution to the EthDevtools list!

**Comment by NatalieChin80** [comment]
Thank you for the suggestion @pakaplace!! And our pleasure!
